version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CustomerMicroserviceRestAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ox27avn6jd49"
s3_prefix = "CustomerMicroserviceRestAPI"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
