AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customer-microservice-rest-api

  Sample SAM Template for customer-microservice-rest-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java8
    MemorySize: 512
    Environment:
        Variables:
            DEFAULT_COUNTRY: NL
            DEFAULT_CURRENCY: EUR
    
Resources:
  CreateCustomerHandlerLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: . #customer-microservice-prj # folder name where template.yml is.
      Handler: com.horasan.customer.handler.CreateCustomerHandler::handleRequest
      Events:
        CustomerMSCreateEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customers
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomerMicroserviceApi:
    Description: "API Gateway endpoint URL for create a new customer."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/customers/"
  CreateCustomerHandlerLambdaFunction:
    Description: "Create Lambda Function ARN"
    Value: !GetAtt CreateCustomerHandlerLambdaFunction.Arn
  CreateCustomerHandlerLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CreateCustomerHandlerLambdaFunctionRole.Arn
